[build-system]
requires = [
“setuptools>=42”,
“wheel”
]
build-backend = “setuptools.build_meta”


[project.scripts]
simpar_cli = "simpar_cli:cli"

[project]
name = "simpar_cli"
version = "0.0.4"
authors = [
  { name="Darix SAMANI", email="samanidarix@gmail.com" },
]
description = "simple cli for paragraphe recognition"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/darixsamani/simpar_cli/"
"Bug Tracker" = "https://github.com/darixsamani/simpar_cli/issues"